version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  test-template: &test-template   
    docker:
      - image: circleci/python:3.7
    working_directory: ~/src
    steps:
      - checkout:
          path: ~/src/mesures
      - run:
          name: Install requirements
          command: |
            export ROOT_DIR_SRC=~/src          
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "~/src/mesures/requirements.txt"}}
      - run:
          name: Install dependencies
          command: |
            cd ~/src/
            virtualenv venv
            . venv/bin/activate
            cd mesures
            pip install -r requirements.txt          
      - save_cache:
          paths:
            - ~/src/venv
          key: v1-dependencies-{{ checksum "~/src/mesures/requirements.txt"}}
      - run:
          command: |
            cd ~/src/
            . venv/bin/activate
            cd mesures
            mamba --enable-coverage
            coverage report
            coverage html
          name: Test
      - store_artifacts:
          path: ~/src/mesures/htmlcov
          destination: coverage
          name: store_artifacts

  test-py27:
    <<: *test-template
    docker:
      - image: circleci/python:2.7

  test-py37:
    <<: *test-template
    docker:
      - image: circleci/python:3.7

workflows:
  test:
    jobs:
      - test-py37
      - test-py27
