name: Release

on:
  push:
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+-rc[0-9]+'
      - 'v[0-9]+\.[0-9]+\.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
        with:
          strip_v: false
      - name: Run setup
        run: |
          pip install -e .
          python setup.py sdist
      - name: Creating a realease/pre-release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PUB_MASTER_PUSH_TOKEN }}
        with:
          tag_name: ${{steps.tag.outputs.tag}}
          draft: false
          prerelease: ${{ contains(github.ref, '-rc') }}
          generate_release_notes: true
      - name: Publish a Python distribution to PyPI
        if: ${{ contains(github.ref, '-rc') }} == false
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_MASTER_TOKEN }}